
CREATE TABLE [SECTOR] (
    ID INT NOT NULL IDENTITY(1,1),
    SECTOR_CODE VARCHAR(255),
    SECTOR_NAME VARCHAR(255),
    IS_DELETED BIT,
    IS_ENABLED BIT,
    ADD_TIME DATETIME2(7) NOT NULL,
    EDIT_TIME DATETIME2(7),
    PRIMARY KEY (ID)
 );

CREATE TABLE [CHANGE_PASSWORD_REQUEST] (
     ID INT NOT NULL IDENTITY(1,1),
     STATUS VARCHAR(255),
     USER_ID INT NOT NULL,
     ADD_TIME DATETIME2(7) NOT NULL,
     EDIT_TIME DATETIME2(7),
     EXECUTION_TIME DATETIME2(7) NOT NULL,
     PRIMARY KEY (ID)
);

CREATE TABLE [CHANGE_PASSWORD_OTP_REQUEST] (
     OTP_ID INT NOT NULL IDENTITY(1,1),
     CHANGE_PASSWORD_REQUEST_ID INT,
     OTP_VALUE VARCHAR(255) NOT NULL,
     IS_USED BIT NOT NULL,
     ADD_TIME DATETIME2(7) NOT NULL,
     EXPIRE_TIME DATETIME2(7) NOT NULL,
     PRIMARY KEY (OTP_ID)
);


CREATE TABLE [REFRESH_TOKEN] (
     ID INT NOT NULL IDENTITY(1,1),
     TOKEN VARCHAR(255) NOT NULL,
     USER_ID INT,
     IS_USED BIT NOT NULL,
     EXPIRY_DATE DATETIME2(7) NOT NULL,
    CONSTRAINT PK_REFRESH_TOKEN PRIMARY KEY (ID)
);

CREATE TABLE [ROLE] (
    ID INT NOT NULL IDENTITY(1,1),
    NAME VARCHAR(20),
    PRIMARY KEY  (ID)
);

CREATE TABLE [USER_ROLE] (
    USER_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID)
);

CREATE TABLE [USER] (
    ID INT NOT NULL IDENTITY(1,1),
    NAME VARCHAR(50),
    EMAIL VARCHAR(50),
    SECTOR_ID INT,
    PHONE_NUMBER VARCHAR(20),
    USERNAME VARCHAR(20),
    PASSWORD VARCHAR(120),
    ADD_TIME DATETIME2(7),
    EDIT_TIME DATETIME2(7),
    LAST_ACTION_TIME DATETIME2(7),
    LAST_LOGIN_TIME DATETIME2(7),
    CONSTRAINT PK_USER PRIMARY KEY (ID)
);

ALTER TABLE [USER] ADD CONSTRAINT UK_USER UNIQUE (USERNAME);

ALTER TABLE [USER] ADD CONSTRAINT UK_USER_EMAIL UNIQUE (EMAIL);

ALTER TABLE [USER] ADD CONSTRAINT FK_USER_SECTOR FOREIGN KEY (SECTOR_ID) REFERENCES [SECTOR] (ID);

ALTER TABLE [CHANGE_PASSWORD_REQUEST] ADD CONSTRAINT FK_CHANGE_PASSWORD_REQUEST_USER FOREIGN KEY (USER_ID) REFERENCES [USER] (ID);

ALTER TABLE [CHANGE_PASSWORD_OTP_REQUEST] ADD CONSTRAINT FK_CHANGE_PASSWORD_OTP_REQUEST_CHANGE_PASSWORD_REQUEST FOREIGN KEY (CHANGE_PASSWORD_REQUEST_ID) REFERENCES [CHANGE_PASSWORD_REQUEST] (ID);

ALTER TABLE [REFRESH_TOKEN] ADD CONSTRAINT FK_REFRESH_TOKEN_USER FOREIGN KEY (USER_ID) REFERENCES [USER] (ID);

ALTER TABLE [USER_ROLE] ADD CONSTRAINT FK_USER_ROLE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES [ROLE] (ID);

ALTER TABLE [USER_ROLE] ADD CONSTRAINT  FK_USER_ROLE_USER FOREIGN KEY (USER_ID) references [USER] (ID);
