package com.mdc.medic.apimedic.config;

public class Status {
    public static final String DEFAULT_ERROR = "DEFAULT_ERROR";
    public static final String SUCCESSFUL = "SUCCESSFUL";
    public static final String BAD_CREDENTIALS="BAD_CREDENTIALS";
    public static final String USER_REGISTERED_SUCCESSFULLY="USER_REGISTERED_SUCCESSFULLY";
    public static final String USER_DISCONNECTED_SUCCESSFULLY="USER_DISCONNECTED_SUCCESSFULLY";
    public static final String BRANCH_DELETED_SUCCESSFULLY="BRANCH_DELETED_SUCCESSFULLY";
    public static final String BRANCH_ENABLED_SUCCESSFULLY="BRANCH_ENABLED_SUCCESSFULLY";
    public static final String BRANCH_DISABLED_SUCCESSFULLY="BRANCH_DISABLED_SUCCESSFULLY";
    public static final String AGENT_DELETED_SUCCESSFULLY="AGENT_DELETED_SUCCESSFULLY";
    public static final String AGENT_ENABLED_SUCCESSFULLY="AGENT_ENABLED_SUCCESSFULLY";
    public static final String AGENT_DISABLED_SUCCESSFULLY="AGENT_DISABLED_SUCCESSFULLY";
    public static final String RESET_LINK_SENT_SUCCESSFULLY="RESET_LINK_SENT_SUCCESSFULLY";
    public static final String PASSWORD_CHANGED_SUCCESSFULLY="PASSWORD_CHANGED_SUCCESSFULLY";
    public static final String USER_DELETED_SUCCESSFULLY="USER_DELETED_SUCCESSFULLY";
    public static final String USER_ENABLED_SUCCESSFULLY="USER_ENABLED_SUCCESSFULLY";
    public static final String USER_DISABLED_SUCCESSFULLY="USER_DISABLED_SUCCESSFULLY";
    public static final String AGENT_RESET_SUCCESSFULLY="AGENT_RESET_SUCCESSFULLY";



}
